version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.next
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - web

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web
    depends_on:
      - nextjs

networks:
  web:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
