services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.next
    restart: unless-stopped
    ports:
      - "3001:3000"
    networks:
      - web
    environment:
      - NODE_ENV=production

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=malmrose.com
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web
    depends_on:
      - nextjs
      - openwebui

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    volumes:
      - open-webui:/app/backend/data
    networks:
      - web
    env_file:
      - .env
    environment:
      - ENABLE_OAUTH_SIGNUP=True
      - ENABLE_LOGIN_FORM=False
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_OAUTH_SCOPE=${GOOGLE_OAUTH_SCOPE}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
networks:
  web:
    driver: bridge

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  open-webui:
    driver: local