name: Deploy to Ubuntu NUC

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v3

    - name: Deploy with Docker
      run: |
        # Navigate to project directory
        cd ~/nextfolio

        # Pull latest changes
        git pull

        # Check if Docker is installed
        if ! command -v docker &> /dev/null; then
          echo "Docker is not installed. Please install Docker first."
          exit 1
        fi

        # Stop any existing containers and remove them
        echo "Stopping existing containers..."
        sudo docker compose down || echo "No containers to stop."

        # Build and start containers in detached mode
        echo "Building and starting containers..."
        sudo docker compose build --no-cache
        sudo docker compose up -d

        # Check if containers are running
        echo "Checking container status..."
        sudo docker compose ps

        # View recent logs
        echo "Recent container logs:"
        sudo docker compose logs --tail=20

        # Print success message at the end to confirm completion
        echo "Deployment completed successfully!"