name: Deploy to Ubuntu NUC

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Add an explicit timeout
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Deploy to NUC via SCP and SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Print system info for debugging
          echo "=== System Information ==="
          df -h
          free -h
          echo "=========================="
          
          # Create the directory if it doesn't exist
          mkdir -p ~/nextfolio
          
          # Check if repository already exists, remove it if it does
          if [ -d ~/nextfolio/.git ]; then
            echo "Removing existing repository..."
            rm -rf ~/nextfolio
            mkdir -p ~/nextfolio
          fi
          
          # Clone with verbose output and timeout
          echo "Starting clone with 5 minute timeout..."
          timeout 300 git clone --verbose --progress https://github.com/JakeMalmrose/nextfolio.git ~/nextfolio
          
          # Check clone result
          if [ $? -eq 124 ]; then
            echo "Clone operation timed out after 5 minutes"
            exit 1
          elif [ $? -ne 0 ]; then
            echo "Clone failed with error code $?"
            exit 1
          fi
          
          # Navigate to project directory
          cd ~/nextfolio || { echo "Failed to change directory"; exit 1; }
          
          # Print repository info
          echo "=== Repository Information ==="
          ls -la
          git status
          echo "============================="
          
          # Install dependencies with fallback and timeout
          echo "Installing dependencies..."
          timeout 300 npm install --no-fund --no-audit --loglevel info || { echo "npm install failed"; exit 1; }
          
          # Build the application with timeout
          echo "Building application..."
          timeout 300 npm run build || { echo "Build failed"; exit 1; }
          
          # Start or restart with PM2
          echo "Starting/restarting with PM2..."
          pm2 restart nextfolio || pm2 start npm --name "nextfolio" -- start